module.exports = {
  layout_header_title: 'School CI server',
  layout_footer_support: 'Support',
  layout_footer_learning: 'Learning',
  layout_footer_ru: 'Русская версия',
  layout_footer_author: 'Julia Zaretskaya',
  settings_title: 'Settings',
  settings_description:
    'Configure repository connection and synchronization settings.',
  settings_form_repo_label: 'GitHub repository',
  settings_form_repo_placeholder: 'github.com/user-name/repo-name.git',
  settings_form_build_label: 'Build command',
  settings_form_build_placeholder: 'npm run build',
  settings_form_branch_label: 'Main branch',
  settings_form_branch_placeholder: 'master',
  settings_form_period_label: 'Synchronize every',
  settings_form_period_label_after: 'minutes',
  settings_form_period_placeholder: '10',
  settings_controls_save: 'Save',
  settings_controls_cancel: 'Cancel',
  buildsList_controls_showMore: 'Show more',
  settings_msg_controls_open: 'Open settings',
  settings_msg_description:
    'Configure repository connection and synchronization settings',
  pending_msg_description: 'Loading data',
  modal_new_build_title: 'New build',
  modal_new_build_description: 'Enter the commit hash which you want to build.',
  modal_new_build_hash_placeholder: 'Commit hash',
  modal_new_build_controls_run: 'Run build',
  modal_new_build_controls_cancel: 'Cancel',
};
